export function createLocations() {
    const locations = [
        { value: 'TPHCM', label: 'TPHCM' },
        { value: 'Hà Nội', label: 'Hà Nội' },
        { value: 'An Giang', label: 'An Giang' },
        { value: 'BàRịa-VũngTàu', label: 'BàRịa-VũngTàu' },
        { value: 'Bạc Liêu', label: 'Bạc Liêu' },
        { value: 'Bắc Kạn', label: 'Bắc Kạn' },
        { value: 'Bắc Giang', label: 'Bắc Giang' },
        { value: 'Bắc Ninh', label: 'Bắc Ninh' },
        { value: 'Bến Tre', label: 'Bến Tre' },
        { value: 'Bình Dương', label: 'Bình Dương' },
        { value: 'BìnhĐịnh', label: 'Bình Định' },
        { value: 'BìnhPhước', label: 'Bình Phước' },
        { value: 'BìnhThuận', label: 'Bình Thuận' },
        { value: 'Cà Mau', label: 'Cà Mau' },
        { value: 'Cao Bằng', label: 'Cao Bằng' },
        { value: 'Cần Thơ(TP)', label: 'Cần Thơ(TP)' },
        { value: 'Đà Nẵng(TP)', label: 'Đà Nẵng(TP)' },
        { value: 'Đắk Lắk', label: 'Đắk Lắk' },
        { value: 'Đắk Nông', label: 'Đắk Nông' },
        { value: 'Điện Biên', label: 'Điện Biên' },
        { value: 'Đồng Nai', label: 'Đồng Nai' },
        { value: 'Đồng Tháp', label: 'Đồng Tháp' },
        { value: 'Gia Lai', label: 'Gia Lai' },
        { value: 'Hà Giang', label: 'Hà Giang' },
        { value: 'Hà Nam', label: 'Hà Nam' },        
        { value: 'Hà Tây', label: 'Hà Tây' },
        { value: 'Hà Tĩnh', label: 'Hà Tĩnh' },
        { value: 'Hải Dương', label: 'Hải Dương' },
        { value: 'Hải Phòng(TP)', label: 'Hải Phòng(TP)' },
        { value: 'Hòa Bình', label: 'Hòa Bình' },        
        { value: 'Hậu Giang', label: 'Hậu Giang' },
        { value: 'Hưng Yên', label: 'Hưng Yên' },
        { value: 'Khánh Hòa', label: 'Khánh Hòa' },
        { value: 'Kiên Giang', label: 'Kiên Giang' },
        { value: 'Kon Tum', label: 'Kon Tum' },
        { value: 'Lai Châu', label: 'Lai Châu' },
        { value: 'Lào Cai', label: 'LàoCai' },
        { value: 'Lạng Sơn', label: 'Lạng Sơn' },
        { value: 'Lâm Đồng', label: 'Lâm Đồng' },
        { value: 'Long An', label: 'Long An' },
        { value: 'Nam Định', label: 'Nam Định' },
        { value: 'Nghệ An', label: 'Nghệ An' },
        { value: 'Ninh Bình', label: 'Ninh Bình' },
        { value: 'NinhT huận', label: 'Ninh Thuận' },
        { value: 'Phú Thọ', label: 'Phú Thọ' },
        { value: 'Phú Yên', label: 'Phú Yên' },
        { value: 'Quảng Bình', label: 'Quảng Bình' },
        { value: 'Quảng Nam', label: 'Quảng Nam' },
        { value: 'Quảng Ngãi', label: 'Quảng Ngãi' },
        { value: 'Quảng Ninh', label: 'Quảng Ninh' },
        { value: 'Quảng Trị', label: 'Quảng Trị' },
        { value: 'Sóc Trăng', label: 'Sóc Trăng' },
        { value: 'Sơn La', label: 'Sơn La' },
        { value: 'Tây Ninh', label: 'Tây Ninh' },
        { value: 'Thái Bình', label: 'Thái Bình' },
        { value: 'Thái Nguyên', label: 'Thái Nguyên' },
        { value: 'Thanh Hóa', label: 'Thanh Hóa' },
        { value: 'ThừaThiên-Huế', label: 'ThừaThiên-Huế' },
        { value: 'Tiền Giang', label: 'Tiền Giang' },
        { value: 'Trà Vinh', label: 'Trà Vinh' },
        { value: 'Tuyên Quang', label: 'Tuyên Quang' },
        { value: 'Vĩnh Long', label: 'Vĩnh Long' },
        { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
        { value: 'Yên Bái', label: 'Yên Bái' },
    ];
    return locations;
}

export function createInterestings() {
    const interestings = [
        { value: 'Sport', label: 'Sport' },
        { value: 'Healthy', label: 'Healthy' },
        { value: 'Fashion', label: 'Fashion' },
        { value: 'Music', label: 'Music' },
        { value: 'Foods', label: 'Foods' },
    ];
    return interestings;
}

export function createJobs() {
    const jobs = [
        { value: 'Share Link', label: 'Share Link' },
        { value: 'Post Image', label: 'Post Image' },
        { value: 'Live Stream', label: 'Live Stream' },
        { value: 'Check In', label: 'Check In' },
        { value: 'Video', label: 'Video' },
    ];
    return jobs;
}